const upgradeData = [
    {
        id: "0",
        image: require("../assets/icon.png"),
        title: "Clicker upgrade",
        upgradeName: "clickerUpgrade",
        baseCost: 10,
        upgrade: 1,
        costMutlipler: 2,
    },
    {
        id: "1",
        image: require("../assets/favicon.png"),
        title: "First upgrade",
        upgradeName: "upgrade1",
        baseCost: 10,
        upgrade: 2,
        costMutlipler: 2,
    },
    {
        id: "2",
        image: require("../assets/splash-icon.png"),
        title: "Second upgrade",
        upgradeName: "upgrade2",
        baseCost: 20,
        upgrade: 3,
        costMutlipler: 2,
    },
    {
        id: "3",
        image: require("../assets/adaptive-icon.png"),
        title: "Third upgrade",
        upgradeName: "upgrade3",
        baseCost: 30,
        upgrade: 5,
        costMutlipler: 2,
    },
    {
        id: "4",
        image: require("../assets/adaptive-icon.png"),
        title: "Fourth upgrade",
        upgradeName: "upgrade4",
        baseCost: 40,
        upgrade: 8,
        costMutlipler: 2,
    },
    {
        id: "5",
        image: require("../assets/adaptive-icon.png"),
        title: "Fifth upgrade",
        upgradeName: "upgrade5",
        baseCost: 50,
        upgrade: 13,
        costMutlipler: 2,
    },
];

export default upgradeData;
