const upgradeData = [
    {
        id: "0",
        image: require("../../assets/icon.png"),
        title: "Clicker upgrade",
        upgradeName: "clickerUpgrade",
        baseCost: 5,
        costMutlipler: 2,
        passivePointsIncrease: 0,
    },
    {
        id: "1",
        image: require("../../assets/favicon.png"),
        title: "First upgrade",
        upgradeName: "upgrade1",
        baseCost: 10,
        costMutlipler: 2,
        passivePointsIncrease: 0.002,
    },
    {
        id: "2",
        image: require("../../assets/splash-icon.png"),
        title: "Second upgrade",
        upgradeName: "upgrade2",
        baseCost: 20,
        costMutlipler: 2,
        passivePointsIncrease: 0.005,
    },
    {
        id: "3",
        image: require("../../assets/adaptive-icon.png"),
        title: "Third upgrade",
        upgradeName: "upgrade3",
        baseCost: 30,
        costMutlipler: 2,
        passivePointsIncrease: 0.0075,
    },
    {
        id: "4",
        image: require("../../assets/adaptive-icon.png"),
        title: "Fourth upgrade",
        upgradeName: "upgrade4",
        baseCost: 40,
        costMutlipler: 2,
        passivePointsIncrease: 0.01,
    },
    {
        id: "5",
        image: require("../../assets/adaptive-icon.png"),
        title: "Fifth upgrade",
        upgradeName: "upgrade5",
        baseCost: 50,
        costMutlipler: 2,
        passivePointsIncrease: 0.025,
    },
];

export default upgradeData;
